spring:
  application:
    name: procurement-service  

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      service: procurement-service  

logging:
  level:
    root: INFO
    "[com.invent.io]": DEBUG
  file:
    name: ./logs/procurement-service.log  
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"